version: "3.9"

services:
  web:
    image: naborslov/diplom_kts:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_started
    ports:
      - "80:8080"
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./config.yaml:/app/config.yaml

  migration:
    image: naborslov/diplom_kts:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head
    volumes:
      - ./alembic.ini:/app/alembic.ini
      - ./config.yaml:/app/config.yaml

  rabbitmq:
    image: rabbitmq:latest
    hostname: my-rabbit

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

