"""add_ondelete player

Revision ID: 65e8917cdb8d
Revises: b7231ce2cc94
Create Date: 2023-03-16 12:01:56.526816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e8917cdb8d'
down_revision = 'b7231ce2cc94'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_user_id_fkey', 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'user_tg', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key('player_user_id_fkey', 'player', 'user_tg', ['user_id'], ['id'])
    # ### end Alembic commands ###
